apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.21
    path: "/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.21
    path: "/tv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movie-volume
spec:
  capacity:
    storage: 1994Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.21
    path: "/movies"