apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-ingress
  namespace: qbittorrent
spec:
  routes:
  - kind: Rule
    match: Host(`qbit.cluster.local`)
    services:
    - name: qbittorrent
      port: 8084