apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.235.203
  ports:
    - port: 8094
      targetPort: 9696
  selector:
    app: prowlarr
