apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utilities
  name: utilities-nfs-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi