apiVersion: v1
kind: PersistentVolume
metadata:
  name: utilities-nfs-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/internal/pihole"