apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-download-volume
spec:
  capacity:
    storage: 1994Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.21
    path: "/movies"