apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.21 # Shared with Plex
    path: "/qbit-config"