apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: piwigo
  name: piwigo-config-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: piwigo
  name: piwigo-gallery-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
