apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filegator
  name: filegator-nfs-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti