apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      name: http
      targetPort: 8080
  selector:
    name: qbittorrent
