apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
  namespace: qbittorrent
  labels:
    name: qbittorrent
spec:
  replicas: 2
  selector:
    matchLabels:
      name: qbittorrent
  template:
    metadata:
      labels:
        name: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: dyonr/qbittorrentvpn
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env:
        - name: VPN_ENABLED
          value: "yes"
        - name: VPN_TYPE
          value: "openvpn"
        - name: LAN_NETWORK
          value: 192.168.50.0/24
        - name: INSTALL_PYTHON3
          value: "yes"
        envFrom:
        - secretRef:
            name: qbittorrent-vpn-secret
        ports:
        - containerPort: 8080
        - containerPort: 8999
        volumeMounts:
        - name: qbittorrent-config-volume
          mountPath: "/config"
        - name: qbittorrent-download-volume
          mountPath: "/downloads"
      volumes:
      - name: qbittorrent-config-volume
        persistentVolumeClaim:
          claimName: qbittorrent-config-claim
      - name: qbittorrent-download-volume
        persistentVolumeClaim:
          claimName: qbittorrent-download-claim