apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: qbittorrent
  name: qbittorrent-download-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1994Gi