apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: piwigo
  name: mariadb-data-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi