apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgres
  name: postgres-volume-claim
spec:
  storageClassName: longhorn-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
