apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: qbittorrent-config-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
