apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.109.184
  ports:
    - port: 8095
      name: http
      targetPort: 8080
  selector:
    name: qbittorrent
