apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: utilities-ingress
  namespace: utilities
spec:
  routes:
  - kind: Rule
    match: Host(`pi.cluster.local`)
    services:
    - name: pihole
      namespace: utilities
      port: 8080


