apiVersion: v1
kind: PersistentVolume
metadata:
  name: dvr-media-volume
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.20
    path: "/repository/Security"
