apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dvr
  name: dvr-media-volume-claim
spec:
  storageClassName: nfs-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 190Gi
