apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dvr
  name: dvr-config-volume-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dvr
  name: dvr-commands-volume-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi