apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-nfs-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/internal/plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: plex-nfs-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti