kind: Service
apiVersion: v1
metadata:
  namespace: plex
  name: plex-nfs-service
spec:
  type: ClusterIP
  clusterIP: 10.43.0.21
  selector:
    role: plex-nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: mountd
      port: 20048