kind: Pod
apiVersion: v1
metadata:
  name: plex-nfs-server
  namespace: plex
  labels:
    role: plex-nfs-server
spec:
  containers:
  - name: nfs-server-container
    image: itsthenetwork/nfs-server-alpine:latest
    env: 
    - name: SHARED_DIRECTORY
      value: '/shared'
    ports:
    - name: nfs
      containerPort: 2049
    - name: mountd
      containerPort: 20048
    - name: rpcbind
      containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
    - name: plex-nfs-pv
      mountPath: /shared
  volumes:
  - name: plex-nfs-pv
    persistentVolumeClaim:
      claimName: plex-nfs-pvc
  nodeSelector:
    kubernetes.io/arch: amd64