apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitcoach-postgres
  namespace: fitcoach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitcoach-postgres
  template:
    metadata:
      labels:
        app: fitcoach-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: fitcoach-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: fitcoach-postgres-volume-claim
