apiVersion: v1
kind: PersistentVolume
metadata:
  name: filegator-nfs-volume
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/raid/nfs"
