apiVersion: v1
kind: PersistentVolume
metadata:
  name: filegator-volume
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.20
    path: "/repository"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filegator-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.0.20
    path: "/private"