apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.73.209
  ports:
    - port: 8093
      targetPort: 8093
  selector:
    app: radarr
