kind: Pod
apiVersion: v1
metadata:
  name: notification-service-nfs-server
  namespace: notification-service
  labels:
    role: notification-service-nfs-server
spec:
  containers:
  - name: nfs-server-container
    image: itsthenetwork/nfs-server-alpine:latest
    env: 
    - name: SHARED_DIRECTORY
      value: '/shared'
    ports:
    - name: nfs
      containerPort: 2049
    - name: mountd
      containerPort: 20048
    - name: rpcbind
      containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
    - name: notification-service-nfs-pv
      mountPath: /shared
  volumes:
  - name: notification-service-nfs-pv
    persistentVolumeClaim:
      claimName: notification-service-nfs-pvc
    