apiVersion: v1
kind: PersistentVolume
metadata:
  name: notification-service-nfs-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/internal/notification-service"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: notification-service
  name: notification-service-nfs-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi