apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: tv-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: movie-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: download-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
