apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.56.9
  ports:
    - port: 8092
      targetPort: 8989
  selector:
    app: sonarr
