apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: valheim
  name: valheim-config-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi