apiVersion: v1
kind: Service
metadata:
  name: valheim
  namespace: valheim
spec:
  type: LoadBalancer
  ports:
    - port: 2456
      name: gameport
      targetPort: 2456
      protocol: UDP
    - port: 2457
      name: queryport
      targetPort: 2457
      protocol: UDP
  selector:
    name: valheim
