apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: matrix
  name: synapse-data-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
