apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mosquitto
  name: mosquitto-config-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mosquitto
  name: mosquitto-data-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mosquitto
  name: mosquitto-log-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
