apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dvr
  name: config-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dvr
  name: commands-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dvr
  name: media-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
