apiVersion: v1
kind: Service
metadata:
  name: dvr
  namespace: dvr
spec:
  selector:
    name: dvr
  ports:
  - name: http
    protocol: TCP
    port: 8090
    targetPort: 8090
  - name: stun
    protocol: UDP
    port: 3478
    targetPort: 3478
  - name: stream1
    protocol: UDP
    port: 50000
    targetPort: 50000
  - name: stream2
    protocol: UDP
    port: 50001
    targetPort: 50001
  - name: stream3
    protocol: UDP
    port: 50002
    targetPort: 50002
  - name: stream4
    protocol: UDP
    port: 50003
    targetPort: 50003
  - name: stream5
    protocol: UDP
    port: 50004
    targetPort: 50004
  - name: stream6
    protocol: UDP
    port: 50005
    targetPort: 50005
  - name: stream7
    protocol: UDP
    port: 50006
    targetPort: 50006
  - name: stream8
    protocol: UDP
    port: 50007
    targetPort: 50007
  - name: stream9
    protocol: UDP
    port: 50008
    targetPort: 50008
  - name: stream10
    protocol: UDP 
    port: 50009
    targetPort: 50009
  - name: stream11
    protocol: UDP
    port: 50010
    targetPort: 50010
  type: LoadBalancer
