apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix-cert
  namespace: matrix
spec:
  secretName: matrix-matgautron-dev-cert-key
  dnsNames:
    - matrix.matgautron.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
