apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: jellyfin-config-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: jellyfin-cache-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi