apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.25.33
  ports:
    - port: 8098
      name: http
      targetPort: 8096
  selector:
    app: jellyfin
