apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.0.31
    path: "/data"