apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.194.66
  ports:
    - port: 8091
      targetPort: 32400
  selector:
    app: plex
