apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utilities
  name: pihole-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
