apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utilities
  name: pihole-pvc-dns
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
