apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: utilities
  name: pihole-pvc-dns
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
