apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sftpgo
  name: sftpgo-data-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sftpgo
  name: sftpgo-config-pvc
spec:
  storageClassName: hdd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi