apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: n8n
  name: n8n-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi