apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: matrix
  name: synapse-postgres-volume-claim
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
