apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-postgres-config
  namespace: matrix
  labels:
    app: synapse-postgres
data:
  POSTGRES_DB: synapse
  POSTGRES_USER: synapse
  # Not accessible from outside the cluster
  POSTGRES_PASSWORD: test123
  POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF-8"