apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-postgres
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse-postgres
  template:
    metadata:
      labels:
        app: synapse-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: synapse-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: synapse-postgres-volume-claim