apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filegator
  name: filegator-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filegator
  name: filegator-config-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi