apiVersion: v1
kind: Service
metadata:
  name: filegator
  namespace: filegator
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      name: http
      targetPort: 80
  selector:
    name: filegator
