apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-volume-dns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.0.30
    path: "/etc-dnsmasq.d"