apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-volume-claim
  namespace: notification-service
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  # Use the NFS server with the ClusterIP 10.43.0.30
  volumeName: postgres-data-volume