kind: Pod
apiVersion: v1
metadata:
  name: hdd-nfs-server
  namespace: storage
  labels:
    role: hdd-nfs-server
spec:
  containers:
    - name: nfs-server-container
      image: itsthenetwork/nfs-server-alpine:latest
      env:
        - name: SHARED_DIRECTORY
          value: '/shared'
      ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
      securityContext:
        privileged: true
      volumeMounts:
        - name: hdd-nfs-pv
          mountPath: /shared
  volumes:
    - name: hdd-nfs-pv
      persistentVolumeClaim:
        claimName: hdd-nfs-pvc
  nodeSelector:
    kubernetes.io/arch: amd64
---
kind: Service
apiVersion: v1
metadata:
  namespace: storage
  name: hdd-nfs-service
spec:
  type: ClusterIP
  clusterIP: 10.43.0.31
  selector:
    role: hdd-nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: rpcbind
      port: 111
    - name: mountd
      port: 20048
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdd-nfs-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/hdd/nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: storage
  name: hdd-nfs-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti