apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nas
  name: nas-media-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/hdd/nasmedia"