kind: Pod
apiVersion: v1
metadata:
  name: nas-media-server
  namespace: nas
  labels:
    role: nas-media-server
spec:
  containers:
  - name: nfs-server-container
    image: itsthenetwork/nfs-server-alpine:latest
    env: 
    - name: SHARED_DIRECTORY
      value: '/shared'
    ports:
    - name: nfs
      containerPort: 2049
    - name: mountd
      containerPort: 20048
    - name: rpcbind
      containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
    - name: nas-media-volume
      mountPath: /shared
  volumes:
  - name: nas-media-volume
    persistentVolumeClaim:
      claimName: nas-media-pvc
  nodeSelector:
    kubernetes.io/arch: amd64