apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homeassistant
  name: homeassistant-nfs-pvc
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi