apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-nfs-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/internal/homeassistant"