apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.25.35
  ports:
    - port: 8097
      name: http
      targetPort: 5055
  selector:
    app: overseerr
