apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homeassistant
  name: homeassistant-pvc
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
