apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nginx-test
  name: nginx-test-claim
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc-ssd
  namespace: nginx-test
spec:
  containers:
    - name: app-container
      image: nginx:latest
      volumeMounts:
      - name: nginx-test-nfs-volume
        mountPath: /shared
  volumes:
    - name: nginx-test-nfs-volume
      persistentVolumeClaim:
        claimName: nginx-test-claim