apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr-deployment
  namespace: media
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6767
          volumeMounts:
            - name: bazarr-config-pv
              mountPath: "/config"
            - name: bazarr-tv-pv
              mountPath: "/tv"
            - name: bazarr-movie-pv
              mountPath: "/movies"
      volumes:
        - name: bazarr-config-pv
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: bazarr-tv-pv
          persistentVolumeClaim:
            claimName: tv-pvc
        - name: bazarr-movie-pv
          persistentVolumeClaim:
            claimName: movie-pvc
