apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  type: LoadBalancer
  clusterIP: 10.43.235.244
  ports:
    - port: 8091
      targetPort: 6767
  selector:
    app: bazarr
