apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: playground
  name: mongodb-data-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
