apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: playground
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: passcode
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: passcode
          - name: MONGO_INITDB_DATABASE
            value: passcode
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data-volume
          mountPath: /data/db
      volumes:
      - name: mongodb-data-volume
        persistentVolumeClaim:
          claimName: mongodb-data-claim