apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: satisfactory
  name: satisfactory-config-claim
spec:
  storageClassName: longhorn-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
