apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/internal/mongodb